services:
  flask-app:
    build: ./backend
    ports:
      - "6000:6000"
    environment:
      FLASK_ENV: development 
    volumes:
      - ./backend:/app
    image: indoor_aqi-back

  react-app:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - flask-app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    image: indoor_aqi-front
