services:
  - type: web
    name: flask-app
    env: docker
    repo: https://github.com/atharvadalvi07/Indoor_aqi
    branch: main
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: FLASK_ENV
        value: development
    plan: starter
    ports:
      - port: 5000

  - type: web
    name: react-app
    env: docker
    repo: https://github.com/atharvadalvi07/Indoor_aqi
    branch: main
    dockerfilePath: frontend/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: CHOKIDAR_USEPOLLING
        value: true
    plan: starter
    ports:
      - port: 3000
    dependsOn:
      - flask-app
